### ISSUE TITLE
bot sync: conflict markers>>> === <<< into main code

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#2954] opened 2022-04-16 12:22 UTC
![Screenshot_20220416-083749~2](https://user-images.githubusercontent.com/6558304/163674048-e7fe10e1-b500-468c-b0a9-dc6856df24c6.png)

It is hard to find all the changes/conflicts inside bot's sync pr when working online,

github is not aware of them and let you merge the markers

the snapshot is the actual German master code 

I found it easier to make our own eng merge locally

should warn it

**Comment by iliakan** [comment] 2022-04-16 16:13
You  mean the bot merges such thing automatically?

**Comment by joaquinelio** [comment] 2022-04-16 18:10
> You mean the bot merges such thing automatically?

no,

when doing merges online, 
github lets you navigate conflicts ("mark as solved" "next conflict" )
and does not let you merge a pr without all of them marked as solved

github doesn't see conflicts in Bot's PR so the tools are not there 
 and merge btn is enabled.

easy to miss changes and markers

**Comment by iliakan** [comment] 2022-04-16 18:11
As I remember, when sync PR is created, it commits conflicts to it, expecting them to be resolved.

**Comment by joaquinelio** [comment] 2022-04-16 18:27
it should.

manually made pr, ok
bot made pr, no ok 

now I have proof in last german merge,
just look at it //de.

you tell him :-)

**Comment by joaquinelio** [comment] 2022-04-16 18:34
i mean 
conflicts are marked ok, the git way

but github does not help in solving them 
the way it does with pr made by hand.
it is easy to miss them and hit merge.

**Comment by iliakan** [comment] 2022-04-16 18:42
yes, need to look for `>>>` in text.

**Comment by iliakan** [comment] 2022-04-16 18:43
It's intended for merging in code editors, not in Github UI.

**Comment by joaquinelio** [comment] 2022-04-16 19:02
ok, if that's the answer, I'm good.
a warning would be nice

suggestion better than warning, 

reviewers need to check  no conflicted changes too, the editor is better tool for that.

**Comment by iliakan** [comment] 2022-04-16 19:04
I'll close this, as it seems to work as intended.

**Closed by iliakan** 2022-04-16 19:04 UTC

**Comment by joaquinelio** [comment] 2022-04-16 20:03
yes, poorly
 xD
dont worry, you're still the best.

the problem is what you expect,
github has good enough tools, if you are used to it, you may fall in the trap.

sorry for that
I'm a problem sniffer,
i got crazy when I saw the trap closed.
